name: 编译xbs

on:
  workflow_dispatch:
  schedule:
   - cron: 0 17 * * 5
env:
  TZ: Asia/Shanghai
  UPLOAD_1: true 
  XBS     : false
  
jobs:
  build:
    name: 下载
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: 下载文件
        run: |
          wget https://raw.githubusercontent.com/bgvioletsky/DownloadApp/main/version.sh
          chmod +x version.sh
          # wget https://hub.gitmirror.com/https://github.com/bgvioletsky/DownloadApp/releases/download/v0.0.3/xbs-linux-arm64 -O xbs
          # chmod +x xbs
          # xbs x-j -i ALL/mulShare.xbs -o mulShare.json
      - name: 设置变量
        id: compile
        run: |
          echo "version=$(bash version.sh)" >> $GITHUB_ENV
          echo "bgcode=$(date +'%Y.%m.%d-%H%M')" >> $GITHUB_ENV
    
      - name: 上传文件1
        if: env.UPLOAD_1 == 'true' && !cancelled()
        uses: actions/upload-artifact@main
        with:
            name: bgcode.xbs
            path: ./ALL/mulShare.xbs
 
      - name: 创建链接
        id: ss
        run: |  
            echo "下载软件app">> release.txt


      - name: 发布到release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.version }}
          body_path: release.txt
          files: ./ALL/mulShare.xbs
