name: 编译xbs

on:
  workflow_dispatch:
  schedule:
   - cron: 0 17 * * 5
env:
  TZ: Asia/Shanghai
  UPLOAD_1: true 
  XBS     : false
  
jobs:
  build:
    name: 下载
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: 下载文件
        run: |
          wget https://raw.githubusercontent.com/bgvioletsky/DownloadApp/main/version.sh
          chmod +x version.sh
          wget https://github.com/bgvioletsky/DownloadApp/releases/download/v0.0.3/xbs-linux-amd64 -O xbs
          chmod +x xbs
          ./b.sh ALL/mulShare.json
      - name: 设置变量
        id: compile
        run: |
          echo "version=$(bash version.sh)" >> $GITHUB_ENV
          echo "bgcode=$(date +'%Y.%m.%d-%H%M')" >> $GITHUB_ENV
    
      - name: commit
        run: |
            git config --local user.email "44770157@qq.com"
            git config --local user.name "bgcode"
            git pull
            git add .
            git commit -m "update $(date +'%Y-%m-%d %H:%M:%S')"  
      - name:  Push changes
        uses:  ad-m/github-push-action@master
        with:  
          branch: main
          github_token: ${{ secrets.MY_GIT_TOKEN }}
      - name: 创建链接
        id: ss
        run: |  
            echo "下载软件app">> release.txt


      - name: 发布到release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.version }}
          body_path: release.txt
          files: ./ALL/*
      - name: 删除老的Releases
        uses: dev-drprasad/delete-older-releases@v0.1.0
        with:
            keep_latest: 3
            delete_tags: true
        env:
            GITHUB_TOKEN: ${{ secrets.MY_GIT_TOKEN }}